// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BringToFront() {
  return window['go']['service']['AppService']['BringToFront']();
}

export function CheckAdmin() {
  return window['go']['service']['AppService']['CheckAdmin']();
}

export function CheckTunStatus() {
  return window['go']['service']['AppService']['CheckTunStatus']();
}

export function CheckUpdates() {
  return window['go']['service']['AppService']['CheckUpdates']();
}

export function CloseConnection(arg1) {
  return window['go']['service']['AppService']['CloseConnection'](arg1);
}

export function DNSResolverOwners() {
  return window['go']['service']['AppService']['DNSResolverOwners']();
}

export function DownloadAndInstallUpdate(arg1, arg2) {
  return window['go']['service']['AppService']['DownloadAndInstallUpdate'](arg1, arg2);
}

export function ExportSettings() {
  return window['go']['service']['AppService']['ExportSettings']();
}

export function FetchSubscription(arg1) {
  return window['go']['service']['AppService']['FetchSubscription'](arg1);
}

export function GetAppVersion() {
  return window['go']['service']['AppService']['GetAppVersion']();
}

export function GetConnections() {
  return window['go']['service']['AppService']['GetConnections']();
}

export function GetHistory() {
  return window['go']['service']['AppService']['GetHistory']();
}

export function GetKillSwitchState() {
  return window['go']['service']['AppService']['GetKillSwitchState']();
}

export function GetSettings() {
  return window['go']['service']['AppService']['GetSettings']();
}

export function GetSubscriptions() {
  return window['go']['service']['AppService']['GetSubscriptions']();
}

export function ImportClipboard(arg1) {
  return window['go']['service']['AppService']['ImportClipboard'](arg1);
}

export function ImportSettings() {
  return window['go']['service']['AppService']['ImportSettings']();
}

export function InitTray(arg1) {
  return window['go']['service']['AppService']['InitTray'](arg1);
}

export function IsQuitting() {
  return window['go']['service']['AppService']['IsQuitting']();
}

export function MutexHandle() {
  return window['go']['service']['AppService']['MutexHandle']();
}

export function NotifyWindowHidden() {
  return window['go']['service']['AppService']['NotifyWindowHidden']();
}

export function NotifyWindowShown() {
  return window['go']['service']['AppService']['NotifyWindowShown']();
}

export function OpenLogsFolder() {
  return window['go']['service']['AppService']['OpenLogsFolder']();
}

export function PingServer(arg1) {
  return window['go']['service']['AppService']['PingServer'](arg1);
}

export function Quit() {
  return window['go']['service']['AppService']['Quit']();
}

export function RebuildTrayProfiles() {
  return window['go']['service']['AppService']['RebuildTrayProfiles']();
}

export function RebuildTrayServers() {
  return window['go']['service']['AppService']['RebuildTrayServers']();
}

export function RebuildTrayToggles() {
  return window['go']['service']['AppService']['RebuildTrayToggles']();
}

export function RequestAdmin() {
  return window['go']['service']['AppService']['RequestAdmin']();
}

export function RestartXray(arg1, arg2, arg3) {
  return window['go']['service']['AppService']['RestartXray'](arg1, arg2, arg3);
}

export function SaveHistory(arg1) {
  return window['go']['service']['AppService']['SaveHistory'](arg1);
}

export function SaveLogs(arg1) {
  return window['go']['service']['AppService']['SaveLogs'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['service']['AppService']['SaveSettings'](arg1);
}

export function SaveSubscriptions(arg1) {
  return window['go']['service']['AppService']['SaveSubscriptions'](arg1);
}

export function SelectAndConnectServer(arg1) {
  return window['go']['service']['AppService']['SelectAndConnectServer'](arg1);
}

export function SessionTraffic() {
  return window['go']['service']['AppService']['SessionTraffic']();
}

export function SetContext(arg1) {
  return window['go']['service']['AppService']['SetContext'](arg1);
}

export function SetGlobalHotkeys(arg1, arg2, arg3) {
  return window['go']['service']['AppService']['SetGlobalHotkeys'](arg1, arg2, arg3);
}

export function SetMutexHandle(arg1) {
  return window['go']['service']['AppService']['SetMutexHandle'](arg1);
}

export function SetQuitting(arg1) {
  return window['go']['service']['AppService']['SetQuitting'](arg1);
}

export function SetSystemProxy(arg1) {
  return window['go']['service']['AppService']['SetSystemProxy'](arg1);
}

export function SetWindowVisible(arg1) {
  return window['go']['service']['AppService']['SetWindowVisible'](arg1);
}

export function StartAutoUpdateScheduler() {
  return window['go']['service']['AppService']['StartAutoUpdateScheduler']();
}

export function StartXray(arg1, arg2, arg3) {
  return window['go']['service']['AppService']['StartXray'](arg1, arg2, arg3);
}

export function StopAutoUpdateScheduler() {
  return window['go']['service']['AppService']['StopAutoUpdateScheduler']();
}

export function StopXray() {
  return window['go']['service']['AppService']['StopXray']();
}

export function UpdateSubscriptionNow(arg1) {
  return window['go']['service']['AppService']['UpdateSubscriptionNow'](arg1);
}

export function ValidateDNS(arg1) {
  return window['go']['service']['AppService']['ValidateDNS'](arg1);
}
