// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CheckAdmin():Promise<boolean>;

export function CheckUpdates():Promise<Record<string, any>>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function FetchSubscription(arg1:string):Promise<Array<string>>;

export function GetSettings():Promise<string>;

export function GetSubscriptions():Promise<string>;

export function ImportClipboard(arg1:string):Promise<Array<string>>;

export function InitTray(arg1:Array<number>):Promise<void>;

export function NotifyWindowHidden():Promise<void>;

export function NotifyWindowShown():Promise<void>;

export function PingServer(arg1:string):Promise<number>;

export function RebuildTrayServers():Promise<void>;

export function RequestAdmin():Promise<void>;

export function RestartXray(arg1:string,arg2:string,arg3:boolean):Promise<Record<string, any>>;

export function RunDiagnostics():Promise<string>;

export function SaveSettings(arg1:string):Promise<boolean>;

export function SaveSubscriptions(arg1:string):Promise<boolean>;

export function SelectAndConnectServer(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetSystemProxy(arg1:boolean):Promise<void>;

export function SetWindowVisible(arg1:boolean):Promise<void>;

export function StartAutoUpdateScheduler():Promise<void>;

export function StartXray(arg1:string,arg2:string,arg3:boolean):Promise<Record<string, any>>;

export function StopAutoUpdateScheduler():Promise<void>;

export function StopXray():Promise<Record<string, any>>;

export function UpdateAllSubscriptions():Promise<void>;

export function UpdateTrayStatus(arg1:string):Promise<void>;
