// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAdmin() {
  return window['go']['service']['AppService']['CheckAdmin']();
}

export function CheckUpdates() {
  return window['go']['service']['AppService']['CheckUpdates']();
}

export function FetchSubscription(arg1) {
  return window['go']['service']['AppService']['FetchSubscription'](arg1);
}

export function GetSettings() {
  return window['go']['service']['AppService']['GetSettings']();
}

export function GetSubscriptions() {
  return window['go']['service']['AppService']['GetSubscriptions']();
}

export function ImportClipboard(arg1) {
  return window['go']['service']['AppService']['ImportClipboard'](arg1);
}

export function InitTray(arg1) {
  return window['go']['service']['AppService']['InitTray'](arg1);
}

export function NotifyWindowHidden() {
  return window['go']['service']['AppService']['NotifyWindowHidden']();
}

export function NotifyWindowShown() {
  return window['go']['service']['AppService']['NotifyWindowShown']();
}

export function PingServer(arg1) {
  return window['go']['service']['AppService']['PingServer'](arg1);
}

export function RebuildTrayServers() {
  return window['go']['service']['AppService']['RebuildTrayServers']();
}

export function RequestAdmin() {
  return window['go']['service']['AppService']['RequestAdmin']();
}

export function RestartXray(arg1, arg2, arg3) {
  return window['go']['service']['AppService']['RestartXray'](arg1, arg2, arg3);
}

export function RunDiagnostics() {
  return window['go']['service']['AppService']['RunDiagnostics']();
}

export function SaveSettings(arg1) {
  return window['go']['service']['AppService']['SaveSettings'](arg1);
}

export function SaveSubscriptions(arg1) {
  return window['go']['service']['AppService']['SaveSubscriptions'](arg1);
}

export function SelectAndConnectServer(arg1) {
  return window['go']['service']['AppService']['SelectAndConnectServer'](arg1);
}

export function SetContext(arg1) {
  return window['go']['service']['AppService']['SetContext'](arg1);
}

export function SetSystemProxy(arg1) {
  return window['go']['service']['AppService']['SetSystemProxy'](arg1);
}

export function SetWindowVisible(arg1) {
  return window['go']['service']['AppService']['SetWindowVisible'](arg1);
}

export function StartAutoUpdateScheduler() {
  return window['go']['service']['AppService']['StartAutoUpdateScheduler']();
}

export function StartXray(arg1, arg2, arg3) {
  return window['go']['service']['AppService']['StartXray'](arg1, arg2, arg3);
}

export function StopAutoUpdateScheduler() {
  return window['go']['service']['AppService']['StopAutoUpdateScheduler']();
}

export function StopXray() {
  return window['go']['service']['AppService']['StopXray']();
}

export function UpdateAllSubscriptions() {
  return window['go']['service']['AppService']['UpdateAllSubscriptions']();
}

export function UpdateTrayStatus(arg1) {
  return window['go']['service']['AppService']['UpdateTrayStatus'](arg1);
}
